server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/products_dev?useSSL=false"
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR
    com.archil: DEBUG

cors:
  allowed:
    origins: "*"

oauth2:
  server: http://127.0.0.1:8081
  clientid: j4yc5uq84922y24nt7f3
  clientsecret: 9WBYMUFJBaj9RwUrF49m